base_path: "."

components:
  terraform:
    base_path: "components/terraform"

stacks:
  base_path: "stacks"
  name_pattern: "{stage}"
  excluded_paths:
    - "defaults/**/*"
  included_paths:
    - "/**/*"
