vars:
  stage: prod

import:
  - defaults/prod
  - defaults/s3_cdn

components:
  terraform:
    s3_cdn:
      vars:
        stage: "prod"
        bucket_name: "olafherebucket"
        domain_name: "olafhere.click"
        zone_name: "olafhere.click"
