name: Workflows for TerraCloud
description: Atmos workflows for managing TerraCloud

workflows:
  ### DEV
  plan-all-dev:
    stack: dev
    steps:
      - command: terraform plan s3

  apply-all-dev:
    stack: dev
    steps:
      - command: terraform apply s3 -auto-approve

  destroy-all-dev:
    stack: dev
    steps:
      - command: terraform destroy s3 -auto-approve

  ### PROD
  plan-all-prod:
    stack: prod
    steps:
      - command: terraform plan s3_cdn

  apply-all-prod:
    stack: prod
    steps:
      - command: terraform apply s3_cdn -auto-approve

  destroy-all-prod:
    stack: prod
    steps:
      - command: terraform destroy s3_cdn -auto-approve
